### ISSUE TITLE
DNS解析逻辑

### ISSUE THREAD

**Issue by Matthew-Harris-36** [PuerNya/sing-box#11]
### Operating system

Linux

### System version

debian12

### Installation type

Original sing-box Command Line

### Version

```shell
1.10.0-alpha.29-067c81a7
```

### Description

有人讲P核即使开启了fake-ip，当进行路由规则匹配时，遇到IP段的，会再次DNS解析。而官核就会跳过。请问是这样吗？我在P核WIKI里没有找到相关说明。有人让我到github building分支看配置/route里的文件，我也没找到相关说明。所以只能问下大佬了。

### Reproduction

有人讲P核即使开启了fake-ip，当进行路由规则匹配时，遇到IP段的，会再次DNS解析。而官核就会跳过。请问是这样吗？

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by kingsey** [comment]
ip规则加参数"skip_resolve": true

**Comment by Matthew-Harris-36** [comment]
@kingsey 看来默认是这样的。能解释下为什么采取这样的默认策略吗？

**Comment by sharkcpt** [comment]
什么时候更新1.10.3 ？大佬

**Comment by PuerNya** [comment]
> @kingsey 看来默认是这样的。能解释下为什么采取这样的默认策略吗？

遵循 ipondemand 逻辑设计，为了匹配 ip 兜底规则
