### ISSUE TITLE
【功能请求】能否给outbound_providers加一个订阅前缀功能

### ISSUE THREAD

**Issue by suikasisy** [PuerNya/sing-box#8]
### Operating system

Linux

### System version

sing-box-1.9.3-57ff1bd5

### Installation type

Original sing-box Command Line

### Description

比如：
```
{
  "outbound_providers": [
    {
      "type": "",
      "tag": "",
      "path": "",
      "healthcheck_url": "https://www.gstatic.com/generate_204",
      "healthcheck_interval": "1m",
      "override_dialer": {},
      "prefix": "我是前缀",
      "suffix": "我是后缀",
    }
  ]
}
```

如果不支持前缀，那么订阅多个地址中，有重复命名的节点，会导致冲突，内核现有的解决方案是自动给冲突的节点加[1]后缀，但是会导致额外的问题，比如[1]后缀在每次内核重启后会随机分配，导致手动指定的节点左右横跳。谢谢。

### Reproduction

无

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by starifly** [comment]
支持，实用功能，也能区分机场节点
